import { useQuery } from "@tanstack/react-query";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { FiDollarSign, FiHome, FiCheckCircle, FiDownload } from "react-icons/fi";
import api from "../../api/axios.js";
import { useAuth } from "../../context/AuthContext.jsx";

const MONTH_NAMES = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

export default function OwnerHome() {
  const { user } = useAuth();

  const { data, isLoading } = useQuery({
    queryKey: ["owner-analytics"],
    queryFn: () => api.get("/bookings/owner-analytics").then((r) => r.data),
  });

  const chartData = (() => {
    const now = new Date();
    return Array.from({ length: 12 }, (_, i) => {
      const d = new Date(now.getFullYear(), now.getMonth() - 11 + i, 1);
      const match = data?.monthlyEarnings?.find(
        (m) => m._id.year === d.getFullYear() && m._id.month === d.getMonth() + 1
      );
      return { month: MONTH_NAMES[d.getMonth()], earnings: match?.earnings || 0 };
    });
  })();

  const downloadPDF = async () => {
    const { default: jsPDF } = await import("jspdf");
    const { default: autoTable } = await import("jspdf-autotable");

    const doc = new jsPDF();

    // Header
    doc.setFillColor(2, 132, 199);
    doc.rect(0, 0, 210, 40, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("NestQuest", 14, 18);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text("Monthly Earnings Report", 14, 30);
    doc.text(`Owner: ${user?.name}`, 120, 22);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 120, 30);

    // Summary
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Summary", 14, 55);

    autoTable(doc, {
      startY: 60,
      head: [["Metric", "Value"]],
      body: [
        ["Total Earnings", `BDT ${(data?.totalEarnings || 0).toLocaleString()}`],
        ["Total Properties", data?.totalProperties || 0],
        ["Total Approved Bookings", data?.totalBookings || 0],
      ],
      headStyles: { fillColor: [2, 132, 199], textColor: 255 },
      styles: { fontSize: 11 },
    });

    // Monthly table
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Monthly Earnings (Last 12 Months)", 14, doc.lastAutoTable.finalY + 15);

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 20,
      head: [["Month", "Earnings (BDT)"]],
      body: chartData.map((r) => [r.month, r.earnings.toLocaleString()]),
      headStyles: { fillColor: [2, 132, 199], textColor: 255 },
      styles: { fontSize: 11 },
    });

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by NestQuest Platform", 14, 285);
    doc.text(`${new Date().toISOString()}`, 120, 285);

    doc.save(`NestQuest-Earnings-${new Date().toLocaleDateString()}.pdf`);
  };

  const summaryCards = [
    { label: "Total Earnings", value: `৳${(data?.totalEarnings || 0).toLocaleString()}`, icon: FiDollarSign, color: "bg-green-50 text-green-600" },
    { label: "Total Properties", value: data?.totalProperties || 0, icon: FiHome, color: "bg-primary-50 text-primary-600" },
    { label: "Approved Bookings", value: data?.totalBookings || 0, icon: FiCheckCircle, color: "bg-accent-50 text-accent-600" },
  ];

  if (isLoading) return <div className="flex justify-center py-20"><div className="loader" /></div>;

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-display font-bold text-dark-900">Dashboard Overview</h1>
        <button onClick={downloadPDF} className="btn-primary flex items-center gap-2 py-2 px-4 text-sm">
          <FiDownload /> Download PDF Report
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-8">
        {summaryCards.map((c) => (
          <div key={c.label} className="card p-6 flex items-center gap-4">
            <div className={`w-12 h-12 rounded-2xl flex items-center justify-center ${c.color}`}>
              <c.icon size={22} />
            </div>
            <div>
              <p className="text-gray-500 text-sm">{c.label}</p>
              <p className="text-2xl font-display font-bold text-dark-900">{c.value}</p>
            </div>
          </div>
        ))}
      </div>

      <div className="card p-6">
        <h2 className="text-lg font-display font-bold text-dark-900 mb-1">Monthly Earnings</h2>
        <p className="text-gray-400 text-sm mb-6">Last 12 months earnings from approved bookings</p>
        <ResponsiveContainer width="100%" height={300}>
          <LineChart data={chartData}>
            <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
            <XAxis dataKey="month" tick={{ fontSize: 12, fill: "#94a3b8" }} />
            <YAxis tick={{ fontSize: 12, fill: "#94a3b8" }} tickFormatter={(v) => `৳${(v/1000).toFixed(0)}k`} />
            <Tooltip
              formatter={(value) => [`৳${value.toLocaleString()}`, "Earnings"]}
              contentStyle={{ borderRadius: "12px", border: "none", boxShadow: "0 4px 20px rgba(0,0,0,0.1)" }}
            />
            <Line type="monotone" dataKey="earnings" stroke="#0284c7" strokeWidth={2.5}
              dot={{ fill: "#0284c7", strokeWidth: 2, r: 4 }}
              activeDot={{ r: 6, fill: "#0284c7" }} />
          </LineChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}
